name: usb_debug_checker
description: "A Flutter plugin to check if USB debugging is enabled on Android."
version: 0.0.1
homepage:

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.nadeem.usb_debug_checker
        pluginClass: UsbDebugCheckerPlugin
